### ISSUE TITLE
NullPointerException / race condition?

### ISSUE THREAD

**Issue by sboettcher** [RADAR-CNS/radar-commons-android#28]
I noticed what seems to be a possible race condition, when disconnecting and immediately reconnecting a device via bluetooth:

```
   FATAL EXCEPTION: main
      Process: org.radarcns.detail, PID: 23034
      java.lang.RuntimeException: Error receiving broadcast Intent { act=org.radarcns.android.DeviceStatusListener.Status flg=0x10 (has extras) } in org.radarcns.android.device.DeviceServiceConnection$1@5535db7
...
       Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object org.radarcns.android.device.DeviceManager.getState()' on a null object reference
          at org.radarcns.android.device.DeviceService.startRecording(DeviceService.java:402)
          at org.radarcns.android.device.DeviceService$DeviceBinder.startRecording(DeviceService.java:437)
          at org.radarcns.android.device.BaseServiceConnection.startRecording(BaseServiceConnection.java:93)
          at org.radarcns.android.MainActivity.startScanning(MainActivity.java:425)
          at org.radarcns.android.MainActivity$7.run(MainActivity.java:492)
          at android.app.Activity.runOnUiThread(Activity.java:5524)
          at org.radarcns.android.MainActivity.deviceStatusUpdated(MainActivity.java:475)
          at org.radarcns.android.device.DeviceServiceConnection$1.onReceive(DeviceServiceConnection.java:54)
...
```
https://github.com/RADAR-CNS/radar-commons-android/blob/550991410e3525c81cf32255909f3503306b4f51/src/main/java/org/radarcns/android/device/DeviceService.java#L402

The problem is apparently that the device manager is set to `null` (during the disconnect) while the service is already starting a new recording/manager. Tested with a Biovotion device that is always disconnected immediately after connecting, and reconnected again, over and over. The exception doesn't throw every time.
This was never seen with an E4 for obvious reasons.

A quick fix I did, but don't know if this is the best way to handle this:
```diff
--- a/src/main/java/org/radarcns/android/device/DeviceService.java
+++ b/src/main/java/org/radarcns/android/device/DeviceService.java
@@ -382,11 +382,10 @@ public abstract class DeviceService<T extends BaseDeviceState> extends Service i
     }
 
     public BaseDeviceState startRecording(@NonNull Set<String> acceptableIds) {
-        DeviceManager localManager = getDeviceManager();
         if (key.getUserId() == null) {
             throw new IllegalStateException("Cannot start recording: user ID is not set.");
         }
-        if (localManager == null) {
+        while (getDeviceManager() == null) {
             logger.info("Starting recording");
             synchronized (this) {
                 if (deviceScanner == null) {
```

**Comment by afolarin** [comment]
@yatharthranjan observed this disconnect/reconnect cycle with biovotion on UDOO but not with the mobile phone

**Comment by yatharthranjan** [comment]
Yes, on the phone it works perfectly. Don't know if there is some problem in the app or the UDOO itself

**Comment by sboettcher** [comment]
To be clear the disconnect/reconnect cycle is artificially introduced by me, I am making the device disconnect itself when it is on a charger so that another one can connect.

**Comment by strangepleasures** [comment]
I'm now working on a big restructuring of commons-android, basically moving most of the logic from MainActivity to the new issue. It should fix this issue (and will probably introduce a couple of new issues).

**Comment by sboettcher** [comment]
Looks fixed by the various restructuring changes. Will reopen if I see it again.
